
name: Build
on: [push, pull_request]

env:
  DOTNET_NOLOGO: 1

jobs:
  windows:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore src/RazorBlade.sln

      - name: Internal Check
        run: dotnet build --configuration DebugExternalLib src/RazorBlade.Analyzers/RazorBlade.Analyzers.csproj

      - name: Build
        run: dotnet build --configuration Release src/RazorBlade.sln

      - name: Pack
        run: dotnet pack --configuration Release --no-build src/RazorBlade.sln

      - name: Test
        run: dotnet test --configuration Release --no-build src/RazorBlade.sln

      - name: Upload NuGet
        uses: actions/upload-artifact@v2
        with:
          name: NuGet
          path: output/*.nupkg
